/*
 * Subscription Manager
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package subscriptionManager

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"subscriptionManager/util"

	"github.com/gin-gonic/gin"
	"github.com/stripe/stripe-go/v72"
	"github.com/stripe/stripe-go/webhook"
	// "github.com/stripe/stripe-go/v72/checkout/session"
)

// PaymentsStripewebhookPost - Return stripe webhook page.\"
func PaymentsStripewebhookPost(c *gin.Context) {
	config, err := util.LoadConfig(".")
	if err != nil {
		log.Fatal("cannot load config:", err)
	}
	stripe.Key = config.Stripe.StripeAPI

	const MaxBodyBytes = int64(65536)
	c.Request.Body = http.MaxBytesReader(c.Writer, c.Request.Body, MaxBodyBytes)
	log.Println("request body", c.Request.Body)

	body, err := ioutil.ReadAll(c.Request.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading request body: %v\n", err)
		c.Status(http.StatusServiceUnavailable)
		return
	}
	fmt.Fprintf(os.Stdout, "Got body: %s\n", body)
	// Pass the request body and Stripe-Signature header to ConstructEvent, along with the webhook signing key
	// You can find your endpoint's secret in your webhook settings
	endpointSecret := "whsec_73b5bd351e4f441c19178ff6389a0a3b368d375b8aa31d65fa68d141035d2c0b"
	event, err := webhook.ConstructEvent(body, c.Request.Header.Get("Stripe-Signature"), endpointSecret)

	if err != nil {
		fmt.Fprintf(os.Stderr, "Error verifying webhook signature: %v\n", err)
		c.Status(http.StatusBadRequest) // Return a 400 error on a bad signature
		return
	}
	// Handle the checkout.session.completed event
	if event.Type == "checkout.session.completed" {
		var session stripe.CheckoutSession
		err := json.Unmarshal(event.Data.Raw, &session)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error parsing webhook JSON: %v\n", err)
			c.Status(http.StatusBadRequest)
			return
		}

		// Fulfill the purchase...
		FulfillOrder(session)
	}
	// w.WriteHeader(http.StatusOK)
	// })
	// c.Status(http.StatusOK)
	c.JSON(http.StatusOK, gin.H{})
}

func FulfillOrder(session stripe.CheckoutSession) {
	// TODO: fill me in
}
