# API-first development with OpenAPI
openapi: '3.0.1'
info:
  title: 'Subscription Manager'
  version: 0.0.1
servers:
  - url: http://localhost/api
    description: Development server
security:
  - oauth: [jhipster, email, profile]
  - openId: [jhipster, email, profile]    
paths:
  /health:
    get:
      tags:
      - Health Check Endpoint
      responses:
        "200":
          description: "Success"
  /plans:
    get:
      tags:
      - Plan Related Endpoints
      summary: Returns a list of available subscription plans."
      responses:
        "200":
          description: "The response includes a json payload that represents a list of APlan instances."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfAPlans'
  /plans/current:
    get:
      tags:
      - Plan Related Endpoints
      summary: Returns an instance of APlan that a logged on user is currently using."
      responses:
        "200":
          description: "The response includes a json payload that represents an instance of APlan."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APlan'
  /payments/checkout:
    get:
      tags:
      - Payments Checkout
      summary: Returns an stripe checkout page."
      parameters:
      - name: "price_id"
        in: "query"
        required: true
        description: "set price id"
        example: price_1LECZyKUSkDFrC1EroX3h7NW
        schema:
          type: string
      responses:
        "200":
          description: "Returns an stripe checkout page"
  /payments/stripewebhook:
    post:
      tags:
      - Payments Stripewebhook
      summary: Return stripe webhook page."
      responses:
        "200":
          description: "The response includes a json payload that represents an instance of APlan."
components:
  schemas:
    APlan:
      title: API Object that contains details of a subscription plan.
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
        recurrence:
          type: integer
    ListOfAPlans:
      type: object
      properties:
        plans:
          type: array
          items:
            $ref: '#/components/schemas/APlan'
  securitySchemes:
    oauth:
      type: oauth2
      description: OAuth2 authentication with KeyCloak
      flows:
        authorizationCode:
          authorizationUrl: http://localhost/auth/realms/officekube/protocol/openid-connect/auth
          tokenUrl: http://localhost/auth/realms/officekube/protocol/openid-connect/token
          # authorizationUrl: https://keycloak.dev.workspacenow.cloud/auth/realms/officekube/protocol/openid-connect/auth
          # tokenUrl: https://keycloak.dev.workspacenow.cloud/auth/realms/officekube/protocol/openid-connect/token
          scopes:
            jhipster: Jhipster specific claims
            email: Email claims
            profile: Profile claims
    openId:
        type: openIdConnect
        description: OpenID Connect authentication with KeyCloak
        #openIdConnectUrl: http://localhost/auth/realms/officekube/.well-known/openid-configuration
        openIdConnectUrl: https://keycloak.dev.workspacenow.cloud/auth/realms/officekube/.well-known/openid-configuration