# API-first development with OpenAPI
openapi: '3.0.1'
info:
  title: 'Subscription Manager'
  version: 0.0.1
servers:
  - url: http://localhost/api
    description: Development server
paths:
  /health:
    get:
      tags:
      - Health Check Endpoint
      responses:
        "200":
          description: "Success"
  /plans:
    get:
      tags:
      - Plan Related Endpoints
      summary: Returns a list of available subscription plans."
      responses:
        "200":
          description: "The response includes a json payload that represents a list of APlan instances."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfAPlans'
  /plans/current:
    get:
      tags:
      - Plan Related Endpoints
      summary: Returns an instance of APlan that a logged on user is currently using."
      responses:
        "200":
          description: "The response includes a json payload that represents an instance of APlan."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APlan'
  /payments/checkout:
    get:
      tags:
      - Payments Checkout
      summary: Returns an stripe checkout page."
      parameters:
      - name: "priceID"
        in: "query"
        required: true
        description: "insert price id"
        content:
          application/json:  
            schema:
              type: object
              properties:
                price_id:
                  type: string
      responses:
        "200":
          description: "Returns an stripe checkout page"
components:
  schemas:
    APlan:
      title: API Object that contains details of a subscription plan.
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        price:
          type: number
        recurrence:
          type: integer
    ListOfAPlans:
      type: object
      properties:
        plans:
          type: array
          items:
            $ref: '#/components/schemas/APlan'
